[tool.ruff]
target-version = "py38"
select = [
    "I", # isort
    "UP", # pyupgrade
    "F", # pyflakes
    "E", # pycodestyle
    "B", # flake8-bugbear
    "A", # flake8-builtins
    "C4", # flake8-comprehensions
    "PT", # flake8-pytest-style
    "N", # pep8-naming
]

ignore = [
    "E501" # Let black handle line length
]

[tool.black]
line-length = 88
target-version = ['py38']
include = '\.pyi?$'
exclude = '''
(
  /(
      \.eggs
    | \.git
    | \.hg
    | \.mypy_cache
    | \.tox
    | \venv
    | _build
    | buck-out
    | build
    | dist
  )/
  | foo.py
)
'''

[tool.mypy]
disallow_untyped_defs = true
disallow_any_unimported = true
no_implicit_optional = true
check_untyped_defs = true
warn_unused_ignores = true
show_error_codes = true
namespace_packages = true

[[tool.mypy.overrides]]
module = [
    "aioping"
]
ignore_missing_imports = true
